x86-tip: terminate sync when origin merge fails
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>

diff --git a/.tip/bin/tip-sync b/.tip/bin/tip-sync
--- a/.tip/bin/tip-sync
+++ b/.tip/bin/tip-sync
@@ -39,7 +39,10 @@ do
     echo "Updating $B"
     git-checkout $B
     # check whether there's anything to pull from the origin:
-    git-merge origin/$B
+    git-merge origin/$B || {
+	echo "Merge of origin/$B failed. Please fix before syncing again"
+	exit 1;
+    }
 
     # Get the files which have been changed by that topic branch since
     # the last merge of linus tree
